### ISSUE TITLE
Edit charity message and add charity list

### ISSUE THREAD

**Issue by adityaradk** [cubetastic33/toborrights#12]
> The delivery fee is also optional, and up to you. All proceeds go to charity.

I'd like to slightly reword this. Perhaps something like the following:

> All proceeds go in equal part to the Electronic Frontier Foundation, Partners in Health, and Health in Harmony. While we don't require a delivery fee, your contribution to our efforts to raise money for these charities is greatly appreciated.

Also use links to the websites of these organizations.

**Comment by cubetastic33** [comment]
Fixed with [40b63ed](https://github.com/cubetastic33/toborrights/commit/40b63ed76e042ad3e601a3b9914819d52240823e)
