### ISSUE TITLE
Delivery location prompt modifications

### ISSUE THREAD

**Issue by adityaradk** [cubetastic33/toborrights#13]
> Note: only on-campus locations will be taken. No Northside.

Maybe a me-thing, but "No Northside" sounds mildly severe. Maybe change it to something along the lines of:

> We deliver to most locations on campus!
Unfortunately, due to their distance from the heart of campus, we do not deliver to Northside, Canyon Creek Heights, or University Village phases 1-3.
Additionally, if you are in University Commons, please meet your HumanTobor either in the lobby or right outside your Residence Hall.

Obviously a message this large will need a font size reduction. Maybe add newlines too?

Also, the example location of "1.123 RHW, 955 North Loop Road" might give people the idea that they need to enter a full address. Perhaps a change it to something like "sitting on the steps of the student union - i'll wave to you" - perhaps that particular example is quite long, but giving people the idea that they can provide a sorta "natural language" input might be helpful.

**Comment by cubetastic33** [comment]
Fixed with [40b63ed](https://github.com/cubetastic33/toborrights/commit/40b63ed76e042ad3e601a3b9914819d52240823e)
