### ISSUE TITLE
Explain why NetID is needed and prepare user to recieve email

### ISSUE THREAD

**Issue by adityaradk** [cubetastic33/toborrights#14]
Asking for a NetID with no context perhaps might slightly dissuade someone from moving to the next step of an order. Explaining *why* it's needed might be of some use. Here's a draft template message:

> Please provide your UT Dallas NetID. We use it to send you a verification email, helping us fight spam.

This also lets the user know what the next step of the process is before it actually taken place.

**Comment by cubetastic33** [comment]
Fixed with [40b63ed](https://github.com/cubetastic33/toborrights/commit/40b63ed76e042ad3e601a3b9914819d52240823e)
