### ISSUE TITLE
Link at footer of email returns to original webpage

### ISSUE THREAD

**Issue by adityaradk** [cubetastic33/toborrights#15]
The link at the footer of the email sends you right back to the menu listing. Perhaps linking to CACP discord would be more ideal. Alternatively, a link to cometsagainstcomputerprogramming.org might also be good.

**Comment by cubetastic33** [comment]
Does this look okay?
![image](https://user-images.githubusercontent.com/33519300/163721159-a67feb9c-cbe2-4a56-9e52-d4cbcc28be61.png)

**Comment by adityaradk** [comment]
Sure, maybe add a link to the site too?

**Comment by adityaradk** [comment]
Yup!
