### ISSUE TITLE
Browser theme color

### ISSUE THREAD

**Issue by Spaceface16518** [cubetastic33/toborrights#5]
Set a [browser theme color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color), likely the `--accent` color, so that android browsers are styled.

**Comment by cubetastic33** [comment]
Fixed with [b102f70](https://github.com/cubetastic33/toborrights/commit/b102f707a3837c72259ae15d48e5a1ed70f0e9ce). Currently it sets it to the background color, but it could be changed to accent if you think that'll look better.

**Comment by cubetastic33** [comment]
Actually nvm it doesn't seem to be working

**Comment by Spaceface16518** [comment]
does the media query thing work? i've never used that on a theme color meta tag.

**Comment by cubetastic33** [comment]
Actually I think it's working lol
We can reopen if it's not
