### ISSUE TITLE
change base path in build workflow

### ISSUE THREAD

**Issue by Spaceface16518** [cubetastic33/toborrights#9]

**Comment by cubetastic33** [comment]
Is the domain actually specified there? Or is it just the `/toborrights` path that needs to be fixed

**Comment by Spaceface16518** [comment]
yeah you're right, whoops. i was just thinking about the domain name so i wrote that.

**Comment by Spaceface16518** [comment]
fixed by 8bbdfacb2fe8156315fb6ac24898d19279bd915e
